/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crm_project;
import javax.swing.*;
import java.awt.*;
import java.awt.CardLayout;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;

/**
 *
 * @author Jep
 */
public class dashboard extends javax.swing.JFrame {
  
    private backend_customer backendCustomer; 
    private backend_feedback backendFeedback;
    private backend_purchase backendPurchase;
    private CardLayout cardLayout;
    
    
    public dashboard() {
        initComponents();
        cardLayout = (CardLayout)(menuDashboard).getLayout();
        backendCustomer = new backend_customer(this);
        backendCustomer.getTableC();
        backendFeedback = new backend_feedback(this);
        backendFeedback.getTableF();
        backendPurchase = new backend_purchase(this);
        backendPurchase.getTableP();
        customerTable.getModel().addTableModelListener(backendCustomer.NOTEChangeListener());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menuTool = new javax.swing.JPanel();
        customer = new javax.swing.JButton();
        chat = new javax.swing.JButton();
        purchaseHstry = new javax.swing.JButton();
        feedbacks = new javax.swing.JButton();
        products = new javax.swing.JButton();
        ibmLogo = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        menuDashboard = new javax.swing.JPanel();
        customerPanel = new javax.swing.JPanel();
        customerScrollPane = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        bottomPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteTXTAREA = new javax.swing.JTextArea();
        customer_detail = new javax.swing.JLabel();
        customer_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        purchaseHistoryJL = new javax.swing.JLabel();
        FeedbackJL = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        addnewCustomer = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        load_customers = new javax.swing.JButton();
        searchIcon = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        CLOSEBTN = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        chatPanel = new javax.swing.JPanel();
        purchase_historyPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        purchaseTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        orders_cnt = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        customers_cnt = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        earnings_cnt = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        feedbackPanel = new javax.swing.JPanel();
        feedbackScrollPanel = new javax.swing.JScrollPane();
        feedbackTable = new javax.swing.JTable();
        feedback_1Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        num_VerySatisfied = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        feedback_2Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        num_Satisfied = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        feedback_3Panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        num_Neutral = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        feedback_4Panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        num_Disatissfied = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        productsPanel = new javax.swing.JPanel();
        productsScrollPane = new javax.swing.JScrollPane();
        P_MainPanel = new javax.swing.JPanel();
        product1 = new javax.swing.JPanel();
        product1_img = new javax.swing.JLabel();
        product2 = new javax.swing.JPanel();
        product2_img = new javax.swing.JLabel();
        product3 = new javax.swing.JPanel();
        product3_img = new javax.swing.JLabel();
        product4 = new javax.swing.JPanel();
        product4_img = new javax.swing.JLabel();
        product5 = new javax.swing.JPanel();
        product5_img = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setDividerSize(3);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(1405, 823));

        menuTool.setBackground(new java.awt.Color(10, 30, 69));
        menuTool.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customer.setBackground(new java.awt.Color(10, 30, 69));
        customer.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        customer.setForeground(new java.awt.Color(255, 255, 255));
        customer.setText("Customer");
        customer.setBorderPainted(false);
        customer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        menuTool.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 130, -1));

        chat.setBackground(new java.awt.Color(10, 30, 69));
        chat.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        chat.setForeground(new java.awt.Color(255, 255, 255));
        chat.setText("Chat");
        chat.setBorderPainted(false);
        chat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatActionPerformed(evt);
            }
        });
        menuTool.add(chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 130, -1));

        purchaseHstry.setBackground(new java.awt.Color(10, 30, 69));
        purchaseHstry.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        purchaseHstry.setForeground(new java.awt.Color(255, 255, 255));
        purchaseHstry.setText("Purchases");
        purchaseHstry.setBorderPainted(false);
        purchaseHstry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        purchaseHstry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseHstryMouseClicked(evt);
            }
        });
        purchaseHstry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseHstryActionPerformed(evt);
            }
        });
        menuTool.add(purchaseHstry, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 130, -1));

        feedbacks.setBackground(new java.awt.Color(10, 30, 69));
        feedbacks.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        feedbacks.setForeground(new java.awt.Color(255, 255, 255));
        feedbacks.setText("Feedbacks");
        feedbacks.setBorderPainted(false);
        feedbacks.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        feedbacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbacksActionPerformed(evt);
            }
        });
        menuTool.add(feedbacks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, -1));

        products.setBackground(new java.awt.Color(10, 30, 69));
        products.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        products.setForeground(new java.awt.Color(255, 255, 255));
        products.setText("Products");
        products.setBorderPainted(false);
        products.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });
        menuTool.add(products, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 130, -1));

        ibmLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ibm_PNG19658.png"))); // NOI18N
        menuTool.add(ibmLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Logout.setBackground(new java.awt.Color(10, 30, 69));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Logout");
        Logout.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logout button.png"))); // NOI18N
        Logout.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menuTool.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 130, 70));

        jSplitPane1.setLeftComponent(menuTool);

        menuDashboard.setBackground(new java.awt.Color(255, 255, 255));
        menuDashboard.setLayout(new java.awt.CardLayout());

        customerPanel.setBackground(new java.awt.Color(48, 89, 127));
        customerPanel.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        customerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        customerScrollPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        customerScrollPane.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 14)); // NOI18N
        customerScrollPane.setOpaque(false);
        customerScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerScrollPaneMouseClicked(evt);
            }
        });

        customerTable.setBackground(new java.awt.Color(207, 217, 226));
        customerTable.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Middle Name", "Last Name", "Company Name", "Contact No", "Email", "Customer Type", "Note"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.setOpaque(false);
        customerTable.setRowHeight(40);
        customerTable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        customerTable.setShowGrid(false);
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                customerTableMouseReleased(evt);
            }
        });
        customerScrollPane.setViewportView(customerTable);
        if (customerTable.getColumnModel().getColumnCount() > 0) {
            customerTable.getColumnModel().getColumn(0).setResizable(false);
            customerTable.getColumnModel().getColumn(1).setResizable(false);
            customerTable.getColumnModel().getColumn(2).setResizable(false);
            customerTable.getColumnModel().getColumn(3).setResizable(false);
            customerTable.getColumnModel().getColumn(4).setResizable(false);
            customerTable.getColumnModel().getColumn(5).setResizable(false);
            customerTable.getColumnModel().getColumn(6).setResizable(false);
            customerTable.getColumnModel().getColumn(7).setResizable(false);
            customerTable.getColumnModel().getColumn(8).setResizable(false);
        }

        customerPanel.add(customerScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1210, 450));

        bottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        bottomPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        bottomPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        noteTXTAREA.setColumns(20);
        noteTXTAREA.setFont(new java.awt.Font("IBM Plex Sans Light", 0, 12)); // NOI18N
        noteTXTAREA.setRows(5);
        noteTXTAREA.setText(" Customer Note ");
        noteTXTAREA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(noteTXTAREA);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 170));

        bottomPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 430, 170));

        customer_detail.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        customer_detail.setText("Customer Detail");
        bottomPanel.add(customer_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        customer_name.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        customer_name.setText("Customer Name");
        bottomPanel.add(customer_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        jLabel2.setText("Contacts: ");
        bottomPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        jLabel4.setText("Phone number");
        bottomPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        jLabel7.setText("Email");
        bottomPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        jLabel8.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        jLabel8.setText("Purchase ID History:");
        bottomPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        jLabel9.setText("Feedback: ");
        bottomPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        purchaseHistoryJL.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        purchaseHistoryJL.setText("Data");
        bottomPanel.add(purchaseHistoryJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        FeedbackJL.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        FeedbackJL.setText("Data");
        bottomPanel.add(FeedbackJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        customerPanel.add(bottomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 1210, 170));

        topPanel.setBackground(new java.awt.Color(48, 89, 127));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addnewCustomer.setBackground(new java.awt.Color(110, 127, 145));
        addnewCustomer.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        addnewCustomer.setForeground(new java.awt.Color(255, 255, 255));
        addnewCustomer.setText("+ Add New Customer");
        addnewCustomer.setBorderPainted(false);
        addnewCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addnewCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addnewCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addnewCustomerMouseClicked(evt);
            }
        });
        topPanel.add(addnewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 160, -1));

        deletebtn.setBackground(new java.awt.Color(110, 127, 145));
        deletebtn.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn.setText("Delete");
        deletebtn.setBorderPainted(false);
        deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebtnMouseClicked(evt);
            }
        });
        topPanel.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 80, 80, -1));

        load_customers.setBackground(new java.awt.Color(110, 127, 145));
        load_customers.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        load_customers.setForeground(new java.awt.Color(255, 255, 255));
        load_customers.setText("Load Customers");
        load_customers.setBorderPainted(false);
        load_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_customersActionPerformed(evt);
            }
        });
        topPanel.add(load_customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        searchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/whiteSearchIcon (3).png"))); // NOI18N
        searchIcon.setText("jLabel10");
        topPanel.add(searchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 70, -1));

        searchbar.setBackground(new java.awt.Color(114, 142, 168));
        searchbar.setForeground(new java.awt.Color(255, 255, 255));
        searchbar.setText("           Search");
        searchbar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchbarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchbarFocusLost(evt);
            }
        });
        searchbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbarMouseClicked(evt);
            }
        });
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        topPanel.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1210, 40));

        customerPanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1210, 150));

        CLOSEBTN.setFont(new java.awt.Font("IBM Plex Sans SemiBold", 0, 14)); // NOI18N
        CLOSEBTN.setForeground(new java.awt.Color(255, 255, 255));
        CLOSEBTN.setText("        X");
        CLOSEBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLOSEBTNMouseClicked(evt);
            }
        });
        customerPanel.add(CLOSEBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 60, 40));

        jLabel18.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Customer Note");
        customerPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1142, 630, 90, -1));

        menuDashboard.add(customerPanel, "customerCard");

        chatPanel.setBackground(new java.awt.Color(48, 89, 127));
        menuDashboard.add(chatPanel, "chatCard");

        purchase_historyPanel.setBackground(new java.awt.Color(48, 89, 127));
        purchase_historyPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        purchase_historyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        purchaseTable.setBackground(new java.awt.Color(207, 217, 226));
        purchaseTable.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        purchaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Purchase ID", "Customer ID", "Product ID", "Quantity", "Total", "Service Length", "Purchase Date and Time"
            }
        ));
        purchaseTable.setOpaque(false);
        purchaseTable.setRowHeight(40);
        purchaseTable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        purchaseTable.setShowGrid(false);
        jScrollPane2.setViewportView(purchaseTable);

        purchase_historyPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 1180, 440));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orders_cnt.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        orders_cnt.setForeground(new java.awt.Color(255, 255, 255));
        orders_cnt.setText("0");
        jPanel2.add(orders_cnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 40, 40));

        jLabel21.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Orders");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/box.png"))); // NOI18N
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        purchase_historyPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 240, 240));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customers_cnt.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        customers_cnt.setForeground(new java.awt.Color(255, 255, 255));
        customers_cnt.setText("0");
        jPanel3.add(customers_cnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 40, 40));

        jLabel22.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Customers");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user-add.png"))); // NOI18N
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        purchase_historyPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 250, 240));

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        earnings_cnt.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        earnings_cnt.setForeground(new java.awt.Color(255, 255, 255));
        earnings_cnt.setText("0");
        jPanel4.add(earnings_cnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, 40));

        jLabel23.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Earnings");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/coin.png"))); // NOI18N
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        purchase_historyPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 240, 240));

        jLabel17.setFont(new java.awt.Font("IBM Plex Sans SemiBold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("     X");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        purchase_historyPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 50, 40));

        menuDashboard.add(purchase_historyPanel, "purchaseCard");

        feedbackPanel.setBackground(new java.awt.Color(48, 89, 127));
        feedbackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        feedbackScrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        feedbackScrollPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        feedbackTable.setBackground(new java.awt.Color(207, 217, 226));
        feedbackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Product ID", "Feedback Content", "Feedback Rating"
            }
        ));
        feedbackTable.setGridColor(new java.awt.Color(204, 204, 204));
        feedbackTable.setOpaque(false);
        feedbackTable.setRowHeight(40);
        feedbackTable.setShowGrid(false);
        feedbackScrollPanel.setViewportView(feedbackTable);

        feedbackPanel.add(feedbackScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1180, 470));

        feedback_1Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("IBM Plex Sans SemiBold", 0, 18)); // NOI18N
        jLabel1.setText("Very Satisfied");
        feedback_1Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 180, -1, -1));

        num_VerySatisfied.setFont(new java.awt.Font("IBM Plex Sans Light", 1, 24)); // NOI18N
        num_VerySatisfied.setText("0");
        feedback_1Panel.add(num_VerySatisfied, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 13, -1, -1));

        jLabel11.setBackground(new java.awt.Color(102, 153, 255));
        jLabel11.setOpaque(true);
        feedback_1Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/veryFB.png"))); // NOI18N
        feedback_1Panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 60, 210, 110));

        feedbackPanel.add(feedback_1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 220, 210));

        feedback_2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("IBM Plex Sans SemiBold", 0, 18)); // NOI18N
        jLabel3.setText("Satisfied");
        feedback_2Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        num_Satisfied.setFont(new java.awt.Font("IBM Plex Sans Light", 1, 24)); // NOI18N
        num_Satisfied.setText("0");
        feedback_2Panel.add(num_Satisfied, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 13, 20, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/satisfiedFB.png"))); // NOI18N
        feedback_2Panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 70, 210, 110));

        jLabel19.setBackground(new java.awt.Color(102, 153, 255));
        jLabel19.setOpaque(true);
        feedback_2Panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        feedbackPanel.add(feedback_2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 220, 210));

        feedback_3Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("IBM Plex Sans SemiBold", 0, 18)); // NOI18N
        jLabel5.setText("Neutral");
        feedback_3Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        num_Neutral.setFont(new java.awt.Font("IBM Plex Sans Light", 1, 24)); // NOI18N
        num_Neutral.setText("0");
        feedback_3Panel.add(num_Neutral, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 15, -1, -1));

        jLabel26.setBackground(new java.awt.Color(102, 153, 255));
        jLabel26.setOpaque(true);
        feedback_3Panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/neutralFB.png"))); // NOI18N
        feedback_3Panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 60, 210, 110));

        feedbackPanel.add(feedback_3Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 220, 210));

        feedback_4Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("IBM Plex Sans SemiBold", 0, 18)); // NOI18N
        jLabel6.setText("Disatissfied");
        feedback_4Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 180, -1, -1));

        num_Disatissfied.setFont(new java.awt.Font("IBM Plex Sans Light", 1, 24)); // NOI18N
        num_Disatissfied.setText("0");
        feedback_4Panel.add(num_Disatissfied, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 15, -1, -1));

        jLabel10.setBackground(new java.awt.Color(102, 153, 255));
        jLabel10.setOpaque(true);
        feedback_4Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/dissatisfiedFB.png"))); // NOI18N
        feedback_4Panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 210, 110));

        feedbackPanel.add(feedback_4Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 220, 210));

        jLabel14.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Customer Feedbacks");
        feedbackPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("IBM Plex Sans SemiBold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("     X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        feedbackPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 50, 40));

        jLabel16.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total Feedbacks");
        feedbackPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menuDashboard.add(feedbackPanel, "feedbackCard");

        productsPanel.setBackground(new java.awt.Color(48, 89, 127));
        productsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P_MainPanel.setBackground(new java.awt.Color(48, 89, 127));
        P_MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product1.setBackground(new java.awt.Color(255, 255, 255));
        product1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product1_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ibm security.png"))); // NOI18N
        product1.add(product1_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -60, 520, 520));

        P_MainPanel.add(product1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 400));

        product2.setBackground(new java.awt.Color(255, 255, 255));
        product2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product2_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ibm cloud.png"))); // NOI18N
        product2.add(product2_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 5, 380, 390));

        P_MainPanel.add(product2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 410, 400));

        product3.setBackground(new java.awt.Color(255, 255, 255));
        product3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product3_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ibm storage scale.png"))); // NOI18N
        product3.add(product3_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 8, 340, 380));

        P_MainPanel.add(product3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 410, 410));

        product4.setBackground(new java.awt.Color(255, 255, 255));
        product4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product4_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ibm storage.png"))); // NOI18N
        product4.add(product4_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 400));

        P_MainPanel.add(product4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 370, -1));

        product5.setBackground(new java.awt.Color(255, 255, 255));
        product5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product5_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ibm healthcare.png"))); // NOI18N
        product5.add(product5_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 390, 380));

        P_MainPanel.add(product5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 410, 370));

        productsScrollPane.setViewportView(P_MainPanel);

        productsPanel.add(productsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 1240, 550));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/IBM (2) (1).png"))); // NOI18N
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 810));

        productsPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 180));

        jLabel29.setFont(new java.awt.Font("IBM Plex Sans SemiBold", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("IBM Products");
        productsPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 220, -1));

        menuDashboard.add(productsPanel, "productsCard");

        jSplitPane1.setRightComponent(menuDashboard);

        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 840));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void feedbacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbacksActionPerformed
        // TODO add your handling code here:
        cardLayout.show(menuDashboard, "feedbackCard");
        backendFeedback.getRatingSum();
    }//GEN-LAST:event_feedbacksActionPerformed

    private void purchaseHstryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseHstryActionPerformed
        // TODO add your handling code here:
        cardLayout.show(menuDashboard, "purchaseCard");
        backendPurchase.getPurchaseDetails();
    }//GEN-LAST:event_purchaseHstryActionPerformed

    private void chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatActionPerformed
        // TODO add your handling code here:
        cardLayout.show(menuDashboard, "chatCard");
    }//GEN-LAST:event_chatActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
        cardLayout.show(menuDashboard, "customerCard");
    }//GEN-LAST:event_customerActionPerformed

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
        // TODO add your handling code here:
        cardLayout.show(menuDashboard, "productsCard");
    }//GEN-LAST:event_productsActionPerformed

    private void load_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_customersActionPerformed
        // TODO add your handling code here:
        backendCustomer.getTableC();
    }//GEN-LAST:event_load_customersActionPerformed

    private void CLOSEBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEBTNMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CLOSEBTNMouseClicked

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        // TODO add your handling code here:
          backendCustomer.selectcustomerProfile(evt);   
    }//GEN-LAST:event_customerTableMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void customerScrollPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerScrollPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_customerScrollPaneMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void purchaseHstryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseHstryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseHstryMouseClicked

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void searchbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbarMouseClicked
        searchbar.setText("");
    }//GEN-LAST:event_searchbarMouseClicked

    private void addnewCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addnewCustomerMouseClicked
        // TODO add your handling code here:
       new newCustomer().setVisible(true);
    }//GEN-LAST:event_addnewCustomerMouseClicked

    private void searchbarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchbarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarFocusLost

    private void searchbarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchbarFocusGained
        // TODO add your handling code here:
         backendCustomer.searchFunction(searchbar);
    }//GEN-LAST:event_searchbarFocusGained

    private void customerTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_customerTableMouseReleased

    private void deletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Delete Profile?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            backendCustomer.deleteCustomer();
        }
        
    }//GEN-LAST:event_deletebtnMouseClicked
    public void updateCustomerDetails(String customerName, String customerLName, String phoneNumber, String email, String note,  java.util.List<Integer> PurchaseIDs, String cstmrFeedback) {
        customer_name.setText(customerName + " " + customerLName);
        jLabel4.setText(phoneNumber);
        this.jLabel7.setText(email);
        this.noteTXTAREA.setText(note);
         StringBuilder purchaseHistory = new StringBuilder();
          for (Integer purchaseID : PurchaseIDs) {
        purchaseHistory.append(purchaseID).append(", "); // Separate purchase IDs with a comma
    }
        this.purchaseHistoryJL.setText(purchaseHistory.toString());
        this.FeedbackJL.setText(cstmrFeedback);
    }
    
    public void updateFeedbackDetails(int disatissfied, int neutral, int satisfied, int very_satisfied){
        this.num_Disatissfied.setText(Integer.toString(disatissfied));
        this.num_Neutral.setText(Integer.toString(neutral));
        this.num_Satisfied.setText(Integer.toString(satisfied));
        this.num_VerySatisfied.setText(Integer.toString(very_satisfied));
    }
    
    public void updatePurchaseDetails(int orders, int customers, double earnings){
        this.orders_cnt.setText(Integer.toString(orders));
        this.customers_cnt.setText(Integer.toString(customers));
        this.earnings_cnt.setText(String.format("%.2f", earnings));
    }   
    
   public void updateSearchTable(JTable updatedTable) {
    TableModel updatedModel = updatedTable.getModel();
    customerTable.setModel(updatedModel);
    
}
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
             UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLOSEBTN;
    private javax.swing.JLabel FeedbackJL;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel P_MainPanel;
    private javax.swing.JButton addnewCustomer;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton chat;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JButton customer;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JScrollPane customerScrollPane;
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel customer_detail;
    private javax.swing.JLabel customer_name;
    private javax.swing.JLabel customers_cnt;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel earnings_cnt;
    private javax.swing.JPanel feedbackPanel;
    private javax.swing.JScrollPane feedbackScrollPanel;
    private javax.swing.JTable feedbackTable;
    private javax.swing.JPanel feedback_1Panel;
    private javax.swing.JPanel feedback_2Panel;
    private javax.swing.JPanel feedback_3Panel;
    private javax.swing.JPanel feedback_4Panel;
    private javax.swing.JButton feedbacks;
    private javax.swing.JLabel ibmLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton load_customers;
    private javax.swing.JPanel menuDashboard;
    private javax.swing.JPanel menuTool;
    private javax.swing.JTextArea noteTXTAREA;
    private javax.swing.JLabel num_Disatissfied;
    private javax.swing.JLabel num_Neutral;
    private javax.swing.JLabel num_Satisfied;
    private javax.swing.JLabel num_VerySatisfied;
    private javax.swing.JLabel orders_cnt;
    private javax.swing.JPanel product1;
    private javax.swing.JLabel product1_img;
    private javax.swing.JPanel product2;
    private javax.swing.JLabel product2_img;
    private javax.swing.JPanel product3;
    private javax.swing.JLabel product3_img;
    private javax.swing.JPanel product4;
    private javax.swing.JLabel product4_img;
    private javax.swing.JPanel product5;
    private javax.swing.JLabel product5_img;
    private javax.swing.JButton products;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JScrollPane productsScrollPane;
    private javax.swing.JLabel purchaseHistoryJL;
    private javax.swing.JButton purchaseHstry;
    private javax.swing.JTable purchaseTable;
    private javax.swing.JPanel purchase_historyPanel;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JTextField searchbar;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    public JTable getCustomerTable() {
        return customerTable;
    }

    public JTable getFeedbackTable(){
        return feedbackTable;
    }
    
    public JTable getPurchaseTable(){
        return purchaseTable;
    }
    
   

    
    
    



}

