/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crm_project;
import javax.swing.*;
import java.awt.*;
import java.awt.CardLayout;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;

/**
 *
 * @author Jep
 */
public class dashboard extends javax.swing.JFrame {
  
    private backend_customer backendCustomer; 
    private backend_feedback backendFeedback;
    private backend_sales backendSales;
    private CardLayout cardLayout;
    
    
    public dashboard() {
        initComponents();
        cardLayout = (CardLayout)(menuDashboard).getLayout();
        backendCustomer = new backend_customer(this);
        backendCustomer.getTableC();
        backendFeedback = new backend_feedback(this);
        backendFeedback.getTableF();
        backendSales = new backend_sales(this);
        backendSales.getTableP();
        customerTable.getModel().addTableModelListener(backendCustomer.NOTEChangeListener());
        
        CustomHeaderRenderer headerRenderer = new CustomHeaderRenderer();
        customerTable.getTableHeader().setDefaultRenderer(headerRenderer);
        feedbackTable.getTableHeader().setDefaultRenderer(headerRenderer);
        salesTable.getTableHeader().setDefaultRenderer(headerRenderer);
        ProductsRankinginFeedback.getTableHeader().setDefaultRenderer(headerRenderer);
        cstmrFeedback.getTableHeader().setDefaultRenderer(headerRenderer);
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menuTool = new javax.swing.JPanel();
        customer = new javax.swing.JButton();
        purchaseHstry = new javax.swing.JButton();
        feedbacks = new javax.swing.JButton();
        products = new javax.swing.JButton();
        ibmLogo = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        menuDashboard = new javax.swing.JPanel();
        customerPanel = new javax.swing.JPanel();
        customerScrollPane = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        bottomPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteTXTAREA = new javax.swing.JTextArea();
        customer_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        purchaseHistoryJL = new javax.swing.JLabel();
        FeedbackJL = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        customer_detail = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        addnewCustomer = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        load_customers = new javax.swing.JButton();
        searchIcon = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        CLOSEBTN = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        feedbackPanel = new javax.swing.JPanel();
        feedbackScrollPanel = new javax.swing.JScrollPane();
        feedbackTable = new javax.swing.JTable();
        feedback_1Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        num_VerySatisfied = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        feedback_2Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        num_Satisfied = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        feedback_3Panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        num_Neutral = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        feedback_4Panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        num_Disatissfied = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        cstmrFeedback = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ProductsRankinginFeedback = new javax.swing.JTable();
        jLabel36 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Nrate = new javax.swing.JLabel();
        VSrate = new javax.swing.JLabel();
        Drate = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        Srate = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Overallrate = new javax.swing.JLabel();
        iconProduct = new javax.swing.JLabel();
        currentprodID = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        salesPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        earnings_cnt1 = new javax.swing.JLabel();
        earnings_cnt2 = new javax.swing.JLabel();
        earnings_cnt3 = new javax.swing.JLabel();
        earnings_cnt4 = new javax.swing.JLabel();
        earnings_cnt5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        orders_cnt = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        customers_cnt = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        earnings_cnt = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        productsPanel = new javax.swing.JPanel();
        productsScrollPane = new javax.swing.JScrollPane();
        P_MainPanel = new javax.swing.JPanel();
        product1 = new javax.swing.JPanel();
        product1_img = new javax.swing.JLabel();
        product2 = new javax.swing.JPanel();
        product2_img = new javax.swing.JLabel();
        product3 = new javax.swing.JPanel();
        product3_img = new javax.swing.JLabel();
        product4 = new javax.swing.JPanel();
        product4_img = new javax.swing.JLabel();
        product5 = new javax.swing.JPanel();
        product5_img = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setDividerSize(3);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(1405, 823));

        menuTool.setBackground(new java.awt.Color(10, 30, 69));
        menuTool.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        menuTool.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customer.setBackground(new java.awt.Color(10, 30, 69));
        customer.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        customer.setForeground(new java.awt.Color(255, 255, 255));
        customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-customer-40.png"))); // NOI18N
        customer.setText("   Customers");
        customer.setBorder(null);
        customer.setBorderPainted(false);
        customer.setContentAreaFilled(false);
        customer.setFocusPainted(false);
        customer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customer.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/selected.png"))); // NOI18N
        customer.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/selected.png"))); // NOI18N
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        menuTool.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, -1));

        purchaseHstry.setBackground(new java.awt.Color(10, 30, 69));
        purchaseHstry.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        purchaseHstry.setForeground(new java.awt.Color(255, 255, 255));
        purchaseHstry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-purchase-40.png"))); // NOI18N
        purchaseHstry.setText("   Sales");
        purchaseHstry.setBorder(null);
        purchaseHstry.setBorderPainted(false);
        purchaseHstry.setFocusPainted(false);
        purchaseHstry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        purchaseHstry.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/selected2.png"))); // NOI18N
        purchaseHstry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseHstryMouseClicked(evt);
            }
        });
        purchaseHstry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseHstryActionPerformed(evt);
            }
        });
        menuTool.add(purchaseHstry, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, -1));

        feedbacks.setBackground(new java.awt.Color(10, 30, 69));
        feedbacks.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        feedbacks.setForeground(new java.awt.Color(255, 255, 255));
        feedbacks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-comments-40.png"))); // NOI18N
        feedbacks.setText("   Feedbacks");
        feedbacks.setBorder(null);
        feedbacks.setBorderPainted(false);
        feedbacks.setFocusPainted(false);
        feedbacks.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        feedbacks.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/selected3.png"))); // NOI18N
        feedbacks.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/selected3.png"))); // NOI18N
        feedbacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbacksActionPerformed(evt);
            }
        });
        menuTool.add(feedbacks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, -1));

        products.setBackground(new java.awt.Color(10, 30, 69));
        products.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        products.setForeground(new java.awt.Color(255, 255, 255));
        products.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-contact-us-40.png"))); // NOI18N
        products.setText("   Products");
        products.setBorder(null);
        products.setBorderPainted(false);
        products.setFocusPainted(false);
        products.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        products.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/selected4.png"))); // NOI18N
        products.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/selected4.png"))); // NOI18N
        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });
        menuTool.add(products, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, -1));

        ibmLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Group 28 (4).png"))); // NOI18N
        menuTool.add(ibmLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 180, 60));

        Logout.setBackground(new java.awt.Color(10, 30, 69));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Logout");
        Logout.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 60, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-login-30.png"))); // NOI18N
        Logout.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        menuTool.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 770, 120, 60));

        jSplitPane1.setLeftComponent(menuTool);

        menuDashboard.setBackground(new java.awt.Color(255, 255, 255));
        menuDashboard.setLayout(new java.awt.CardLayout());

        customerPanel.setBackground(new java.awt.Color(48, 89, 127));
        customerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        customerPanel.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        customerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        customerScrollPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        customerScrollPane.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 14)); // NOI18N
        customerScrollPane.setOpaque(false);
        customerScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerScrollPaneMouseClicked(evt);
            }
        });

        customerTable.setBackground(new java.awt.Color(207, 217, 226));
        customerTable.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Middle Name", "Last Name", "Company Name", "Contact No", "Email", "Customer Type", "Note"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.setGridColor(new java.awt.Color(0, 0, 0));
        customerTable.setOpaque(false);
        customerTable.setRowHeight(40);
        customerTable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        customerTable.setShowGrid(true);
        customerTable.setShowHorizontalLines(true);
        customerTable.setShowVerticalLines(true);
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                customerTableMouseReleased(evt);
            }
        });
        customerScrollPane.setViewportView(customerTable);
        if (customerTable.getColumnModel().getColumnCount() > 0) {
            customerTable.getColumnModel().getColumn(0).setResizable(false);
            customerTable.getColumnModel().getColumn(0).setPreferredWidth(1);
            customerTable.getColumnModel().getColumn(1).setResizable(false);
            customerTable.getColumnModel().getColumn(2).setResizable(false);
            customerTable.getColumnModel().getColumn(3).setResizable(false);
            customerTable.getColumnModel().getColumn(4).setResizable(false);
            customerTable.getColumnModel().getColumn(5).setResizable(false);
            customerTable.getColumnModel().getColumn(6).setResizable(false);
            customerTable.getColumnModel().getColumn(7).setResizable(false);
            customerTable.getColumnModel().getColumn(8).setResizable(false);
        }

        customerPanel.add(customerScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1210, 450));

        bottomPanel.setBackground(new java.awt.Color(64, 117, 255));
        bottomPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        bottomPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        noteTXTAREA.setEditable(false);
        noteTXTAREA.setBackground(new java.awt.Color(64, 117, 255));
        noteTXTAREA.setColumns(20);
        noteTXTAREA.setFont(new java.awt.Font("IBM Plex Sans Light", 0, 13)); // NOI18N
        noteTXTAREA.setForeground(new java.awt.Color(255, 255, 255));
        noteTXTAREA.setRows(5);
        noteTXTAREA.setText("  Customer Note ");
        noteTXTAREA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        noteTXTAREA.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(noteTXTAREA);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 170));

        bottomPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 430, 170));

        customer_name.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        customer_name.setForeground(new java.awt.Color(255, 255, 255));
        customer_name.setText("Customer Name");
        bottomPanel.add(customer_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contacts: ");
        bottomPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone number");
        bottomPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 200, -1));

        jLabel7.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        bottomPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 80, 200, 20));

        jLabel8.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Purchase ID History:");
        bottomPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Recent Feedback: ");
        bottomPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        purchaseHistoryJL.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        purchaseHistoryJL.setForeground(new java.awt.Color(255, 255, 255));
        purchaseHistoryJL.setText("Data");
        bottomPanel.add(purchaseHistoryJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, -1));

        FeedbackJL.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        FeedbackJL.setForeground(new java.awt.Color(255, 255, 255));
        FeedbackJL.setText("Data");
        bottomPanel.add(FeedbackJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 170, -1));

        jPanel11.setBackground(new java.awt.Color(3, 108, 95));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customer_detail.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        customer_detail.setForeground(new java.awt.Color(255, 255, 255));
        customer_detail.setText("Customer Detail");
        jPanel11.add(customer_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        bottomPanel.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 20));

        jPanel12.setBackground(new java.awt.Color(58, 105, 230));
        bottomPanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 20));

        customerPanel.add(bottomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 1210, 170));

        topPanel.setBackground(new java.awt.Color(48, 89, 127));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addnewCustomer.setBackground(new java.awt.Color(110, 127, 145));
        addnewCustomer.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        addnewCustomer.setForeground(new java.awt.Color(255, 255, 255));
        addnewCustomer.setText("+ Add New Customer");
        addnewCustomer.setBorderPainted(false);
        addnewCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addnewCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addnewCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addnewCustomerMouseClicked(evt);
            }
        });
        topPanel.add(addnewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 160, -1));

        deletebtn.setBackground(new java.awt.Color(110, 127, 145));
        deletebtn.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn.setText("Delete");
        deletebtn.setBorderPainted(false);
        deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebtnMouseClicked(evt);
            }
        });
        topPanel.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 80, 80, -1));

        load_customers.setBackground(new java.awt.Color(110, 127, 145));
        load_customers.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        load_customers.setForeground(new java.awt.Color(255, 255, 255));
        load_customers.setText("Load Customers");
        load_customers.setBorderPainted(false);
        load_customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_customersActionPerformed(evt);
            }
        });
        topPanel.add(load_customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        searchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/whiteSearchIcon (3).png"))); // NOI18N
        searchIcon.setText("jLabel10");
        topPanel.add(searchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 70, -1));

        searchbar.setBackground(new java.awt.Color(114, 142, 168));
        searchbar.setFont(new java.awt.Font("IBM Plex Sans", 0, 14)); // NOI18N
        searchbar.setForeground(new java.awt.Color(255, 255, 255));
        searchbar.setText("           Search");
        searchbar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchbarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchbarFocusLost(evt);
            }
        });
        searchbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbarMouseClicked(evt);
            }
        });
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        topPanel.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 40));

        customerPanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1210, 150));

        CLOSEBTN.setFont(new java.awt.Font("IBM Plex Sans SemiBold", 0, 14)); // NOI18N
        CLOSEBTN.setForeground(new java.awt.Color(255, 255, 255));
        CLOSEBTN.setText("        X");
        CLOSEBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLOSEBTNMouseClicked(evt);
            }
        });
        customerPanel.add(CLOSEBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 60, 40));

        jLabel18.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Customer Note");
        customerPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 630, 90, -1));

        menuDashboard.add(customerPanel, "customerCard");

        feedbackPanel.setBackground(new java.awt.Color(48, 89, 127));
        feedbackPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        feedbackPanel.setForeground(new java.awt.Color(255, 255, 255));
        feedbackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        feedbackScrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        feedbackScrollPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        feedbackTable.setBackground(new java.awt.Color(207, 217, 226));
        feedbackTable.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        feedbackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Product ID", "Feedback Content", "Feedback Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        feedbackTable.setGridColor(new java.awt.Color(0, 0, 0));
        feedbackTable.setOpaque(false);
        feedbackTable.setRowHeight(40);
        feedbackTable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        feedbackTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        feedbackTable.setShowGrid(false);
        feedbackTable.setShowHorizontalLines(true);
        feedbackTable.setShowVerticalLines(true);
        feedbackScrollPanel.setViewportView(feedbackTable);
        if (feedbackTable.getColumnModel().getColumnCount() > 0) {
            feedbackTable.getColumnModel().getColumn(0).setResizable(false);
            feedbackTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            feedbackTable.getColumnModel().getColumn(1).setResizable(false);
            feedbackTable.getColumnModel().getColumn(1).setPreferredWidth(0);
            feedbackTable.getColumnModel().getColumn(2).setResizable(false);
            feedbackTable.getColumnModel().getColumn(3).setResizable(false);
        }

        feedbackPanel.add(feedbackScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 590, 490));

        feedback_1Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("IBM Plex Sans", 0, 18)); // NOI18N
        jLabel1.setText("Very Satisfied");
        feedback_1Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, -1));

        num_VerySatisfied.setFont(new java.awt.Font("IBM Plex Sans Light", 1, 24)); // NOI18N
        num_VerySatisfied.setForeground(new java.awt.Color(255, 255, 255));
        num_VerySatisfied.setText("0");
        feedback_1Panel.add(num_VerySatisfied, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 198, 51));
        jLabel11.setOpaque(true);
        feedback_1Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/veryFB.png"))); // NOI18N
        feedback_1Panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 70, -1, 120));

        feedbackPanel.add(feedback_1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 140, 180));

        feedback_2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("IBM Plex Sans", 0, 18)); // NOI18N
        jLabel3.setText("Satisfied");
        feedback_2Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, -1));

        num_Satisfied.setFont(new java.awt.Font("IBM Plex Sans Light", 1, 24)); // NOI18N
        num_Satisfied.setForeground(new java.awt.Color(255, 255, 255));
        num_Satisfied.setText("0");
        feedback_2Panel.add(num_Satisfied, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 20, -1));

        jLabel19.setBackground(new java.awt.Color(255, 198, 51));
        jLabel19.setOpaque(true);
        feedback_2Panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/satisfiedFB.png"))); // NOI18N
        feedback_2Panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 75, -1, 110));

        feedbackPanel.add(feedback_2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 140, 180));

        feedback_3Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("IBM Plex Sans", 0, 18)); // NOI18N
        jLabel5.setText("Neutral");
        feedback_3Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        num_Neutral.setFont(new java.awt.Font("IBM Plex Sans Light", 1, 24)); // NOI18N
        num_Neutral.setForeground(new java.awt.Color(255, 255, 255));
        num_Neutral.setText("0");
        feedback_3Panel.add(num_Neutral, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel26.setBackground(new java.awt.Color(255, 198, 51));
        jLabel26.setOpaque(true);
        feedback_3Panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/neutralFB.png"))); // NOI18N
        feedback_3Panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        feedbackPanel.add(feedback_3Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 140, 180));

        feedback_4Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("IBM Plex Sans", 0, 18)); // NOI18N
        jLabel6.setText("Dissatisfied");
        feedback_4Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, -1));

        num_Disatissfied.setFont(new java.awt.Font("IBM Plex Sans Light", 1, 24)); // NOI18N
        num_Disatissfied.setForeground(new java.awt.Color(255, 255, 255));
        num_Disatissfied.setText("0");
        feedback_4Panel.add(num_Disatissfied, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 198, 51));
        jLabel10.setOpaque(true);
        feedback_4Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/disatisfiedFB.png"))); // NOI18N
        feedback_4Panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        feedbackPanel.add(feedback_4Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 140, 180));

        jLabel14.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Product Data");
        feedbackPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("IBM Plex Sans SemiBold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("     X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        feedbackPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 50, 40));

        jLabel16.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total Feedbacks");
        feedbackPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel34.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Customer Feedbacks");
        feedbackPanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jPanel7.setBackground(new java.awt.Color(207, 217, 226));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("IBM Plex Sans", 0, 14)); // NOI18N
        jLabel33.setText("Feedback on Product");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 0, 140, 40));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cstmrFeedback.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        cstmrFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer's Feedback"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cstmrFeedback.setGridColor(new java.awt.Color(204, 204, 204));
        cstmrFeedback.setRowHeight(40);
        cstmrFeedback.setSelectionBackground(new java.awt.Color(102, 102, 102));
        cstmrFeedback.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(cstmrFeedback);

        jPanel9.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 220));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 400, -1));

        jLabel35.setFont(new java.awt.Font("IBM Plex Sans", 0, 14)); // NOI18N
        jLabel35.setText("Product Rating");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 20));

        jScrollPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane6MouseClicked(evt);
            }
        });

        ProductsRankinginFeedback.setFont(new java.awt.Font("IBM Plex Sans", 0, 13)); // NOI18N
        ProductsRankinginFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "Product"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductsRankinginFeedback.setGridColor(new java.awt.Color(0, 0, 0));
        ProductsRankinginFeedback.setRowHeight(40);
        ProductsRankinginFeedback.setSelectionBackground(new java.awt.Color(102, 102, 102));
        ProductsRankinginFeedback.setSelectionForeground(new java.awt.Color(255, 255, 255));
        ProductsRankinginFeedback.setShowHorizontalLines(true);
        ProductsRankinginFeedback.setShowVerticalLines(true);
        ProductsRankinginFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsRankinginFeedbackMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(ProductsRankinginFeedback);
        if (ProductsRankinginFeedback.getColumnModel().getColumnCount() > 0) {
            ProductsRankinginFeedback.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 220));

        jLabel36.setFont(new java.awt.Font("IBM Plex Sans", 0, 14)); // NOI18N
        jLabel36.setText("Products Ranking");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 120, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nrate.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        Nrate.setText("0");
        jPanel6.add(Nrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 20, -1));

        VSrate.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        VSrate.setText("0");
        jPanel6.add(VSrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 20, -1));

        Drate.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        Drate.setText("0");
        jPanel6.add(Drate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 20, -1));

        jLabel37.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        jLabel37.setText("Dissatisfied");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel38.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        jLabel38.setText("Very Satisfied");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel39.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        jLabel39.setText("Satisfied");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        Srate.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        Srate.setText("0");
        jPanel6.add(Srate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 20, -1));

        jLabel40.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        jLabel40.setText("Neutral");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel45.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        jLabel45.setText("Overall");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        Overallrate.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        Overallrate.setText("0.0");
        jPanel6.add(Overallrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 160));
        jPanel7.add(iconProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, 190));

        currentprodID.setFont(new java.awt.Font("IBM Plex Sans", 0, 14)); // NOI18N
        currentprodID.setText("1");
        jPanel7.add(currentprodID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, 20));

        feedbackPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 630, 490));

        jPanel8.setBackground(new java.awt.Color(10, 30, 69));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 30, 69), 6, true));
        feedbackPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 1020, 230));

        menuDashboard.add(feedbackPanel, "feedbackCard");

        salesPanel.setBackground(new java.awt.Color(48, 89, 127));
        salesPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        salesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        salesTable.setBackground(new java.awt.Color(207, 217, 226));
        salesTable.setFont(new java.awt.Font("IBM Plex Sans", 0, 12)); // NOI18N
        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Purchase ID", "Customer ID", "Product ID", "Quantity", "Total", "Service Length", "Purchase Date and Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        salesTable.setOpaque(false);
        salesTable.setRowHeight(40);
        salesTable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        salesTable.setShowGrid(false);
        jScrollPane2.setViewportView(salesTable);
        if (salesTable.getColumnModel().getColumnCount() > 0) {
            salesTable.getColumnModel().getColumn(0).setPreferredWidth(1);
            salesTable.getColumnModel().getColumn(1).setPreferredWidth(1);
            salesTable.getColumnModel().getColumn(2).setPreferredWidth(1);
        }

        salesPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 1180, 440));

        jLabel17.setFont(new java.awt.Font("IBM Plex Sans SemiBold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("     X");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        salesPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 50, 40));

        jPanel10.setBackground(new java.awt.Color(10, 30, 69));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 30, 69), 3, true));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(3, 108, 95));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 30, 69), 4, true));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Sales by product");
        jPanel13.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel43.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("IBM Security Maas 360");
        jPanel13.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel44.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("IBM Cloud Pak for Data");
        jPanel13.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel46.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("IBM Storage Defender");
        jPanel13.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel47.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("IBM Power Solution Editions for Healthcare");
        jPanel13.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 40));

        jLabel48.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("IBM Storage Scale System");
        jPanel13.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, -1));

        earnings_cnt1.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        earnings_cnt1.setForeground(new java.awt.Color(255, 255, 255));
        earnings_cnt1.setText("0");
        jPanel13.add(earnings_cnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 20, 20));

        earnings_cnt2.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        earnings_cnt2.setForeground(new java.awt.Color(255, 255, 255));
        earnings_cnt2.setText("0");
        jPanel13.add(earnings_cnt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 20, 20));

        earnings_cnt3.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        earnings_cnt3.setForeground(new java.awt.Color(255, 255, 255));
        earnings_cnt3.setText("0");
        jPanel13.add(earnings_cnt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 20, 20));

        earnings_cnt4.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        earnings_cnt4.setForeground(new java.awt.Color(255, 255, 255));
        earnings_cnt4.setText("0");
        jPanel13.add(earnings_cnt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 20, 20));

        earnings_cnt5.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        earnings_cnt5.setForeground(new java.awt.Color(255, 255, 255));
        earnings_cnt5.setText("0");
        jPanel13.add(earnings_cnt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 20, 20));

        jPanel10.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 240, 240));

        jPanel2.setBackground(new java.awt.Color(255, 198, 51));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 30, 69), 4, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orders_cnt.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        orders_cnt.setForeground(new java.awt.Color(255, 255, 255));
        orders_cnt.setText("0");
        jPanel2.add(orders_cnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 40, 40));

        jLabel21.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Orders");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/box.png"))); // NOI18N
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jPanel10.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 240));

        jPanel3.setBackground(new java.awt.Color(255, 198, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 30, 69), 4, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customers_cnt.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        customers_cnt.setForeground(new java.awt.Color(255, 255, 255));
        customers_cnt.setText("0");
        jPanel3.add(customers_cnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 40, 40));

        jLabel22.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Customers");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user-add.png"))); // NOI18N
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jPanel10.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 250, 240));

        jPanel4.setBackground(new java.awt.Color(255, 198, 51));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 30, 69), 4, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        earnings_cnt.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        earnings_cnt.setForeground(new java.awt.Color(255, 255, 255));
        earnings_cnt.setText("0");
        jPanel4.add(earnings_cnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 130, 40));

        jLabel23.setFont(new java.awt.Font("IBM Plex Sans Medium", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Earnings");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/coin.png"))); // NOI18N
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jPanel10.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 240, 240));

        salesPanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 1180, 280));

        menuDashboard.add(salesPanel, "purchaseCard");

        productsPanel.setBackground(new java.awt.Color(48, 89, 127));
        productsPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        productsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P_MainPanel.setBackground(new java.awt.Color(48, 89, 127));
        P_MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product1.setBackground(new java.awt.Color(255, 255, 255));
        product1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product1_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ibm security (1).png"))); // NOI18N
        product1.add(product1_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, -55, 520, 520));

        P_MainPanel.add(product1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 400));

        product2.setBackground(new java.awt.Color(255, 255, 255));
        product2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product2_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ibm cloud (1).png"))); // NOI18N
        product2.add(product2_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 5, 380, 390));

        P_MainPanel.add(product2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 410, 400));

        product3.setBackground(new java.awt.Color(255, 255, 255));
        product3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product3_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ibm storage scale (1).png"))); // NOI18N
        product3.add(product3_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 340, 370));

        P_MainPanel.add(product3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 410, 400));

        product4.setBackground(new java.awt.Color(255, 255, 255));
        product4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product4_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ibm storage (1).png"))); // NOI18N
        product4.add(product4_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 370, 400));

        P_MainPanel.add(product4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 370, -1));

        product5.setBackground(new java.awt.Color(255, 255, 255));
        product5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product5_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ibm healthcare (1).png"))); // NOI18N
        product5.add(product5_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 390, 380));

        P_MainPanel.add(product5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 410, 400));

        productsScrollPane.setViewportView(P_MainPanel);

        productsPanel.add(productsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 1240, 550));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/IBM (2) (1).png"))); // NOI18N
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 810));

        productsPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 180));

        jLabel29.setFont(new java.awt.Font("IBM Plex Sans", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("IBM Products/ Services");
        productsPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 350, -1));

        menuDashboard.add(productsPanel, "productsCard");

        jSplitPane1.setRightComponent(menuDashboard);

        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 840));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void feedbacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbacksActionPerformed
        // TODO add your handling code here:
        cardLayout.show(menuDashboard, "feedbackCard");
        backendFeedback.getRatingSum();
    }//GEN-LAST:event_feedbacksActionPerformed

    private void purchaseHstryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseHstryActionPerformed
        // TODO add your handling code here:
        cardLayout.show(menuDashboard, "purchaseCard");
        backendSales.getSalesDetails();
    }//GEN-LAST:event_purchaseHstryActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
        cardLayout.show(menuDashboard, "customerCard");
    }//GEN-LAST:event_customerActionPerformed

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
        // TODO add your handling code here:
        cardLayout.show(menuDashboard, "productsCard");
    }//GEN-LAST:event_productsActionPerformed

    private void load_customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_customersActionPerformed
        // TODO add your handling code here:
        backendCustomer.getTableC();
    }//GEN-LAST:event_load_customersActionPerformed

    private void CLOSEBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEBTNMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CLOSEBTNMouseClicked

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        // TODO add your handling code here:
          backendCustomer.selectcustomerProfile(evt);   
    }//GEN-LAST:event_customerTableMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void customerScrollPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerScrollPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_customerScrollPaneMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void purchaseHstryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseHstryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseHstryMouseClicked

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void searchbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbarMouseClicked
        searchbar.setText("");
    }//GEN-LAST:event_searchbarMouseClicked

    private void addnewCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addnewCustomerMouseClicked
        // TODO add your handling code here:
       new newCustomer().setVisible(true);
    }//GEN-LAST:event_addnewCustomerMouseClicked

    private void searchbarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchbarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarFocusLost

    private void searchbarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchbarFocusGained
        // TODO add your handling code here:
         backendCustomer.searchFunction(searchbar);
    }//GEN-LAST:event_searchbarFocusGained

    private void customerTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_customerTableMouseReleased

    private void deletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Delete Profile?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            backendCustomer.deleteCustomer();
        } 
    }//GEN-LAST:event_deletebtnMouseClicked

    private void jScrollPane6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane6MouseClicked

    }//GEN-LAST:event_jScrollPane6MouseClicked

    private void ProductsRankinginFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsRankinginFeedbackMouseClicked
         // TODO add your handling code here:
        backendFeedback.selectProduct(evt);
    }//GEN-LAST:event_ProductsRankinginFeedbackMouseClicked
    public void updateCustomerDetails(String customerName, String customerLName, String phoneNumber, String email, String note,  java.util.List<Integer> PurchaseIDs, String cstmrFeedback) {
        customer_name.setText(customerName + " " + customerLName);
        jLabel4.setText(phoneNumber);
        this.jLabel7.setText(email);
        this.noteTXTAREA.setText(note);
         StringBuilder purchaseHistory = new StringBuilder();
          for (Integer purchaseID : PurchaseIDs) {
        purchaseHistory.append(purchaseID).append(", "); // Separate purchase IDs with a comma
    }
        this.purchaseHistoryJL.setText(purchaseHistory.toString());
        this.FeedbackJL.setText(cstmrFeedback);
    }
    
    public void updateFeedbackDetails(int disatissfied, int neutral, int satisfied, int very_satisfied){
        this.num_Disatissfied.setText(Integer.toString(disatissfied));
        this.num_Neutral.setText(Integer.toString(neutral));
        this.num_Satisfied.setText(Integer.toString(satisfied));
        this.num_VerySatisfied.setText(Integer.toString(very_satisfied));
    }
    
    public void updateSaleDetails(int orders, int customers, double earnings, int prod1, int prod2, int prod3, int prod4, int prod5){
        this.orders_cnt.setText(Integer.toString(orders));
        this.customers_cnt.setText(Integer.toString(customers));
        this.earnings_cnt.setText(String.format("%.2f", earnings));
        this.earnings_cnt1.setText(Integer.toString(prod1));
        this.earnings_cnt2.setText(Integer.toString(prod2));
        this.earnings_cnt3.setText(Integer.toString(prod3));
        this.earnings_cnt4.setText(Integer.toString(prod4));
        this.earnings_cnt5.setText(Integer.toString(prod5));
    }   
    
   public void updateSearchTable(JTable updatedTable) {
    TableModel updatedModel = updatedTable.getModel();
    customerTable.setModel(updatedModel);
    
}
   
   public void updateFeedbackRatings(int disatissfied, int neutral, int satisfied, int very_satisfied, double overall, int prodID) {
       this.VSrate.setText(Integer.toString(very_satisfied));
       this.Srate.setText(Integer.toString(satisfied));
       this.Nrate.setText(Integer.toString(neutral));
       this.Drate.setText(Integer.toString(disatissfied));
       this.Overallrate.setText(String.format("%.2f", overall));
       this.currentprodID.setText(Integer.toString(prodID));
       
       ImageIcon icon;
       switch (prodID) {
           case 1:
               icon = new ImageIcon(getClass().getResource("/imgs/PROD1.png"));
               break;
           case 2:
               icon = new ImageIcon(getClass().getResource("/imgs/PROD2.png"));
               break;
           case 3:
               icon = new ImageIcon(getClass().getResource("/imgs/PROD3.png"));
               break;
           case 4:
               icon = new ImageIcon(getClass().getResource("/imgs/PROD4.png"));
               break;
            case 5:
               icon = new ImageIcon(getClass().getResource("/imgs/PROD5.png"));
               break;
           default:
               throw new AssertionError();
       }
       this.iconProduct.setIcon(icon);
       
   }
   
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
             UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLOSEBTN;
    private javax.swing.JLabel Drate;
    private javax.swing.JLabel FeedbackJL;
    private javax.swing.JPanel Logout;
    private javax.swing.JLabel Nrate;
    private javax.swing.JLabel Overallrate;
    private javax.swing.JPanel P_MainPanel;
    private javax.swing.JTable ProductsRankinginFeedback;
    private javax.swing.JLabel Srate;
    private javax.swing.JLabel VSrate;
    private javax.swing.JButton addnewCustomer;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JTable cstmrFeedback;
    private javax.swing.JLabel currentprodID;
    private javax.swing.JButton customer;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JScrollPane customerScrollPane;
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel customer_detail;
    private javax.swing.JLabel customer_name;
    private javax.swing.JLabel customers_cnt;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel earnings_cnt;
    private javax.swing.JLabel earnings_cnt1;
    private javax.swing.JLabel earnings_cnt2;
    private javax.swing.JLabel earnings_cnt3;
    private javax.swing.JLabel earnings_cnt4;
    private javax.swing.JLabel earnings_cnt5;
    private javax.swing.JPanel feedbackPanel;
    private javax.swing.JScrollPane feedbackScrollPanel;
    private javax.swing.JTable feedbackTable;
    private javax.swing.JPanel feedback_1Panel;
    private javax.swing.JPanel feedback_2Panel;
    private javax.swing.JPanel feedback_3Panel;
    private javax.swing.JPanel feedback_4Panel;
    private javax.swing.JButton feedbacks;
    private javax.swing.JLabel ibmLogo;
    private javax.swing.JLabel iconProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton load_customers;
    private javax.swing.JPanel menuDashboard;
    private javax.swing.JPanel menuTool;
    private javax.swing.JTextArea noteTXTAREA;
    private javax.swing.JLabel num_Disatissfied;
    private javax.swing.JLabel num_Neutral;
    private javax.swing.JLabel num_Satisfied;
    private javax.swing.JLabel num_VerySatisfied;
    private javax.swing.JLabel orders_cnt;
    private javax.swing.JPanel product1;
    private javax.swing.JLabel product1_img;
    private javax.swing.JPanel product2;
    private javax.swing.JLabel product2_img;
    private javax.swing.JPanel product3;
    private javax.swing.JLabel product3_img;
    private javax.swing.JPanel product4;
    private javax.swing.JLabel product4_img;
    private javax.swing.JPanel product5;
    private javax.swing.JLabel product5_img;
    private javax.swing.JButton products;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JScrollPane productsScrollPane;
    private javax.swing.JLabel purchaseHistoryJL;
    private javax.swing.JButton purchaseHstry;
    private javax.swing.JPanel salesPanel;
    private javax.swing.JTable salesTable;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JTextField searchbar;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    public JTable getCustomerTable() {
        return customerTable;
    }

    public JTable getFeedbackTable(){
        return feedbackTable;
    }
    
    public JTable getSalesTable(){
        return salesTable;
    }

    public JTable getCstmrFeedback() {
        return cstmrFeedback;
    }

    public JTable getProductsRanking() {
        return ProductsRankinginFeedback;
    }
    
    
    
    
    
   

    
    
    



}

