/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.crm_project;

import java.awt.FlowLayout;
import java.util.HashSet;
import javax.swing.BoxLayout;


/**
 *
 * @author Jep
 */
public class RankingProductsContainer extends javax.swing.JPanel {

    /**
     * Creates new form RankingProductsContainer
     */
    
    public RankingProductsContainer() {
        initComponents();
        init();
    }

    public void init(){
        rankingList();
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
    }
    
    // add dynamic way to add product name not just iteration i
    public void rankingList(){
        for(int i = 1; i<=5; i++){
            this.add(new Ranking("Product " + i));
        }
        revalidate(); 
        repaint();  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
